version: '3'
services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./React_SAYS
      dockerfile: Dockerfile
    ports:
      - '3000:80'