name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend image
        run: |
          docker build -t rupesh2003/saysfrontend:latest ./React_SAYS
          docker push rupesh2003/saysfrontend:latest

      - name: Build and push backend image
        run: |
          docker build -t rupesh2003/saysbackend:latest ./Server
          docker push rupesh2003/saysbackend:latest
