name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up Docker
        run: docker system prune -a --volumes --force
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend image
        run: |
          docker build -t rupesh2003/saysfrontend:latest ./React_SAYS
          docker push rupesh2003/saysfrontend:latest

      - name: Build and push backend image
        run: |
          docker build -t rupesh2003/saysbackend:latest ./Server
          docker push rupesh2003/saysbackend:latest


  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull images from docker hub
        run: |
          docker pull rupesh2003/saysfrontend:latest
          docker pull rupesh2003/saysbackend:latest
      
      - name: Delete old containers
        run: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)

      - name: Run new containers
        run: |
          docker run -d -p 3000:80 rupesh2003/saysfrontend:latest
          docker run -d -p 5000:5000 rupesh2003/saysbackend:latest 
